### ISSUE TITLE
请问您有实现XNOR-Net这篇论文里的bitcount么？

### ISSUE THREAD

**Issue by GengCauWong** [zhengwy888/binary_ops#1]
我看您在这里 https://github.com/tensorflow/tensorflow/issues/1592 好像说实现了论文 http://arxiv.org/abs/1603.05279 里面的bitcount部分

**Comment by zhengwy888** [comment]
这一行就是bitcount
https://github.com/zhengwy888/binary_ops/blob/master/bnmatmul_op_gpu.cu#L199
